default: &default
  adapter: postgresql
  encoding: utf8
  username: ildarsafin
  host: localhost
  password:
  pool: 5

development:
  <<: *default
  database: goalgame_development

test:
  <<: *default
  database: goalgame_test

production:
  <<: *default
  database: goalgame_production
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
